name: Java CI with Gradle

on:
  push:
    branches:
      - feature-branch
      - main

jobs:
  gradle:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            java: [23]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Execute Gradle test
        run: ./gradlew test
